Adds table payments
kindkiller100/school pull request #14
Opened 2022-12-15 18:34 UTC by 2103364

2022-12-15 18:41 UTC, kindkiller100 approved these changes
ну буковы как буковы, англицкие, апрувед

2022-12-15 18:43 UTC, 2103364 commented
> ну буковы как буковы, англицкие, апрувед

 не буковы а букавы

2022-12-16 14:56 UTC, RomaSapon approved these changes

2022-12-19 16:28 UTC, JuliyaBunas requested changes

2022-12-19 16:28 UTC, JuliyaBunas commented on src/main/resources/scripts/0_initialization.sql
> +    dateOfPayment timestamp NOT NULL,
"OfPayment" not needed

2022-12-19 16:28 UTC, JuliyaBunas commented on src/main/resources/scripts/0_initialization.sql
> +    student_id int NOT NULL REFERENCES subjects(id),
nullable, table students

2022-12-19 16:28 UTC, JuliyaBunas commented on src/main/resources/scripts/0_initialization.sql
> +    auto_ident boolean  DEFAULT NULL,
rename - auto_identified

2022-12-19 16:56 UTC, JuliyaBunas requested changes

2022-12-19 16:56 UTC, JuliyaBunas commented on src/main/resources/scripts/0_initialization.sql
> +    dateTime timestamp NOT NULL,
date_time

2022-12-19 17:01 UTC, JuliyaBunas approved these changes

2022-12-19 17:02 UTC, merged