adds Subject actions: create, edit, delete, get all
kindkiller100/school pull request #44
Opened 2023-01-08 11:33 UTC by PiatrouskiYauhen

adds Subject actions:
create
edit
delete
restore deleted
get all
get all deleted

2023-01-08 19:54 UTC, kindkiller100 reviewed
Как я понял валидацию нужно сделать с помощью аннотаций в Entity, как в этом примере
https://www.baeldung.com/spring-boot-bean-validation

2023-01-09 16:55 UTC, JuliyaBunas requested changes

2023-01-09 16:55 UTC, JuliyaBunas commented on src/main/java/com/school/school/subjects/SubjectController.java
> +    @GetMapping("/{deleted}")
@GetMapping() - returns all not deleted
@GetMapping("/deleted") - returns all deleted

2023-01-09 16:55 UTC, JuliyaBunas commented on src/main/java/com/school/school/subjects/SubjectController.java
> +    public List<Subject> list() {
remove

2023-01-09 16:55 UTC, JuliyaBunas commented on src/main/java/com/school/school/subjects/SubjectController.java
> +    @DeleteMapping("/{id}/{deleted}")
@DeleteMapping("/{id}")
@PutMapping("/{id}/restore")

2023-01-09 16:55 UTC, JuliyaBunas commented on src/main/java/com/school/school/subjects/SubjectController.java
> +        subjectService.setDeleted(id, deleted);
???

2023-01-09 16:55 UTC, JuliyaBunas commented on src/main/java/com/school/school/subjects/SubjectService.java
> +        } else if (title.isEmpty()) {
NPE

2023-01-09 16:55 UTC, JuliyaBunas commented on src/main/java/com/school/school/subjects/SubjectService.java
> +        if (title.isEmpty()) {
separate method validate

2023-01-09 16:55 UTC, JuliyaBunas commented on src/main/java/com/school/school/subjects/SubjectService.java
> +            throw new NotFoundException("Subject with title «" + title + "» already exists.");
BadRequestException

2023-01-09 16:55 UTC, JuliyaBunas commented on src/main/java/com/school/school/subjects/SubjectService.java
> +    //возвращает subject по title
.

2023-01-09 16:55 UTC, JuliyaBunas commented on src/main/java/com/school/school/subjects/SubjectService.java
> +    private boolean existsByTitle(String title) {
At repo: 
    boolean existsByTitle(String title);
    boolean existsByTitleAndIdNotLike(String title, long id);

2023-01-09 16:55 UTC, JuliyaBunas commented on src/main/java/com/school/school/subjects/SubjectService.java
> +        } else if (title.isEmpty()) {
use @NotNull @NotBlank at entity class instead

2023-01-12 16:33 UTC, JuliyaBunas approved these changes

2023-01-12 16:34 UTC, merged