58 Add handling custom validation exceptions
kindkiller100/school pull request #62
Opened 2023-01-19 15:56 UTC by PiatrouskiYauhen

Добавил класс ValidationException.
Добавил соответствующий ExceptionHandler в класс GlobalExceptionHandler.
Сделал сбор ошибок в классах SubjectService, GroupService, LessonService, PaymentService.
Не трогал метод getIfExists(), потому что его выносим в отдельный интерфейс.
Добавил @Valid в двух методах класса SubjectController.
Удалил обработку валидации в классе GroupController.

2023-01-19 16:10 UTC, RomaSapon requested changes
Добавить класс SchoolValidationException в классе LessonService

2023-01-19 16:54 UTC, JuliyaBunas requested changes
Пара замечаний по неймингу, в остальном все отлично, можешь применять своё исключение и в других местах

2023-01-19 16:54 UTC, JuliyaBunas commented on src/main/java/com/school/school/exception_handler/SchoolExceptionHandler.java
> +    @ExceptionHandler(SchoolValidationException.class)
Добавь пожалуйста комментарий, что это обработка валидации бизнес-логики

2023-01-19 16:54 UTC, JuliyaBunas commented on src/main/java/com/school/school/exception_handler/SchoolValidationException.java
> +public class SchoolValidationException extends RuntimeException {
переименовать в ValidationException

2023-01-19 16:54 UTC, JuliyaBunas commented on src/main/java/com/school/school/exception_handler/SchoolValidationException.java
> +    public void addError(String fieldName, String errorMessage) {
переименовать в add или put

2023-01-19 16:54 UTC, JuliyaBunas commented on src/main/java/com/school/school/exception_handler/SchoolValidationException.java
> +    public Map<String, String> getErrors() {
переименовать в get. И так понятно что речь о методах класса exception,  слово Error уже лишнее

2023-01-19 16:54 UTC, JuliyaBunas commented on src/main/java/com/school/school/exception_handler/SchoolValidationException.java
> +package com.school.school.exception_handler;
Заодно пожалуйста переименуй пакет в exceptions

2023-01-20 08:31 UTC, RomaSapon approved these changes

2023-01-22 12:42 UTC, kindkiller100 requested changes
Еще поменять исключения в StudentService и TeacherService

2023-01-23 17:24 UTC, JuliyaBunas requested changes
Также добавить http статус как параметр и сеттер для него, который возвращает объект ValidationException

2023-01-23 17:24 UTC, JuliyaBunas commented on src/main/java/com/school/school/groups/GroupService.java
> +            ValidationException validationException = new ValidationException();
Чтобы не приходилось писать три строки для выбрасываня этого исключения кажый раз, надо добавить конструктор, который принимает две строки (ключ и значение) и сам кладет их в мапу. Тгда здесь будет достаточно написать  throw new ValidationException("id", "Группа с id «" + id + "» не найдена.") вместо 3х строк.

2023-01-23 19:53 UTC, JuliyaBunas approved these changes

2023-01-23 19:55 UTC, merged